# Generated by Django 4.2.4 on 2023-09-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_orderdetails_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
